test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("POSTGRES_DB") {'test'} %>
  username: <%= ENV.fetch("POSTGRES_USER") {'postgres'} %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") {'postgres'} %>